### ISSUE TITLE
Feature Request: new rule prefer-targeted-queries

### ISSUE THREAD

**Issue by benmonro** [Belco90/eslint-plugin-testing-library#20] opened 2019-10-10 20:36 UTC
it would be nice to have an autofixable rule that converted 
this
```
expect(getAllByText('foo')).toHaveLength(1);
```
to this:
```
expect(getByText('foo')).toBeInTheDocument();
```

and similarly:
```
expect(queryAllByText('foo')).toHaveLength(0);
```
to this:
```
expect(queryByText('foo')).toBeNull()
```

if autofix is too hard, at least reporting on it would be nice. :)

**Comment by thomlom** [comment] 2019-10-11 06:15
Hey @benmonro, thank you for contributing again! The rule makes sense and definitely improves the readability of the test files.

The only difficulty I'm seeing right now is that `toBeInTheDocument` requires `jest-dom`. However, it's possible that you extend Jest matchers in a global test setup file. So we'll have to make sure `jest-dom` is referencing in the user's `package.json` before autofixing to `toBeInTheDocument`.

Thus, I'm wondering what to tell the user if he doesn't use `jest-dom`? Should he use `not.toBeNull()`?

Also, for the second example, how about using:

```js
expect(queryAllByText('foo')).toHaveLength(0);
// becomes
expect(queryByText('foo')).not.toBeInTheDocument();
```

instead of `toBeNull`?

What do you think?

**Comment by Belco90** [comment] 2019-10-11 07:59
Hi again! Interesting rule here and few things to discuss.

As @thomlom pointed out, `toBeInTheDocument` is a matcher from `jest-dom` so our plugin can't just autofix that code as we can't assume the matchers available (we could do this through rules options, but I would leave the autofix for a future version). About the reporting, the rule itself seems completely dependent on `jest` matcher when [testing library is not](https://testing-library.com/docs/dom-testing-library/setup#using-without-jest) ([the syntax with chai](https://www.chaijs.com/api/bdd/#method_lengthof) is slightly different for example). This, again, could be done by setting up the rule through options.

After these details I'm not really sure if this rule should apply to this eslint plugin, as it seems really attached to `jest` and `jest-dom` and little bit out of the scope of just testing library. I would like to think about the reporting of the error if some kind of _have length of 1_ is found with proper matcher set up through rules options.

**Comment by thomlom** [comment] 2019-10-11 08:36
@Belco90 It is possible to check if a file is in the system. [eslint-plugin-import](https://github.com/benmosher/eslint-plugin-import/blob/master/src/rules/no-unresolved.js) does it right here. If it's possible to check the contents of a `package.json` file, then we can check whether a user has `jest-dom` in his dependencies or not. I've never done that in an ESLint plugin, so I don't know if that's possible.

But for me this rule can apply to this plugin since `jest-dom` is also in Testing Library's ecosystem.
I think the easiest thing we can do for now is to just report to the user it should use a targeted query if `getAllBy` is used with `toHaveLength(1)` and if `queryBy` is used with `toHaveLength(0)`.

**Comment by Belco90** [comment] 2019-10-11 08:43
About checking file in the system and analyze the package.json: that looks too much for a simple rule, I prefer to just leave it configurable in rule options but not passing `{"jest-dom": true}` but the name of the matcher you want to use for replacement (you are assuming everyone wants to use that one from jest-dom).

About apply the rule to the plugin: again, apart from being attached to jest-dom for the autofix, it's attached to jest for `toHaveLength` matcher and testing library doesn't depend on jest, so we can't look only for that matcher as that would mean assume the user is using jest, which couldn't be the case.

My point here is: remember this is an eslint plugin for testing library, so everything external shouldn't be assumed to be the usual things we use in our envs as they are external things we can't control.

**Comment by benmonro** [comment] 2019-10-11 18:31
yeah i totally get what you guys are saying.  I almost feel like there could be a whole category of rules that are specific to jest-dom.  Part of me wants to just say "this is a jest-dom specific rule" and part of me wants to go the config option route you guys mentioned, but i'm on the fence.  And while i hear what you're saying about this being a testing-library specific plugin, jest-dom is also testing-library specific as well, so I don't think it's necessarily out of scope, but i could be convinced that there should also be an `eslint-plugin-jest-dom` :) . 

whatever you guys decide, i'm just grateful you created this plugin. :)

**Comment by benmonro** [comment] 2019-10-11 18:33
perhaps a phase 1 would be just reporting these errors.  then do the auto-fix in a separate PR (or not at all if it's too hairy)

**Comment by Belco90** [comment] 2019-10-13 18:54
After thinking about it these are my thoughts about this rule.

These are some cases I've identified as valid:
```
expect(getByText('foo')).toBeInTheDocument();

const foo = getByText('foo');
expect(foo).toBeInTheDocument();

expect(queryByText('foo')).toBeDefined();

expect(await findByText('foo')).toBeInTheDocument();

expect(getAllByText('foo')).toHaveLength(2);

expect(getByText('foo')).to.exist;

expect(getAllByText('foo')).to.have.lengthOf(3);
```

And these are some cases I've identified as invalid:
```
expect(queryAllByText('foo')).toHaveLength(1);

const fooList =  getAllByText('foo');
expect(fooList).toHaveLength(1);

expect(await findAllByText('foo')).toHaveLength(1);

expect(getAllByText('foo')).toHaveLength(0);

expect(getAllByText('foo')).to.have.lengthOf(1);

expect(getAllByText('foo')).to.have.lengthOf(0);
```

But then what about this? Should be treated as an error? I guess not but I'm not sure.
```
expect(getAllByText('foo')).not.toHaveLength(1);

expect(getAllByText('foo')).not.toHaveLength(0);
```

As you can see there are tons of edge cases, some of then pending to idenfity. I'm not really convinced yet about it, this looks like they could even be two different rules: one for avoiding checking length of 1 and another one for checking length of 0, and still having the feeling is really attached to jest/chai assertions. We could try implementing a first version just for reporting the error without the autofix and setting the length assert through rule option (but defaults to `toHaveLength`), but could take some to cover all those different edge cases.

What do you think?

**Comment by benmonro** [comment] 2019-10-13 22:12
Makes a lot of sense to me. I dig it

**Comment by thomlom** [comment] 2019-10-14 08:22
It's surely going to take more work. Maybe we could release a first version of the rule just with `jest` and `jest-dom` and then extend it to `chai` and other assertions or add autofix features.

I don't feel like the rule has a lot of edge cases though. In the end, it's just forbidding `toHaveLength(0)` and `toHaveLength(1)` for queries. 
However, after thinking about it, I've changed my mind. This rule does seems more related to Jest (or Chai) assertions than Testing Library. 
In the end, the problem is that `toHaveLength(0)` and `toHaveLength(1)` could be replaced by an assertion more clearer if I got it right. The rule makes sense to me but I have mixed feelings on the fact that it should be included in this plugin.

**Comment by Belco90** [comment] 2019-10-14 08:47
That's the point: `toHaveLength(0)` and `toHaveLength(1)` can be replaced by more accurate assertions, which seems something related to jest/chai but then the reason for that it's that there are betters ways to assert for length 0 or 1 with testing library, as it could be completely fine for another thing tested like checking a util method returns an empty array or just an array with one method. That's why I also have mixed feelings about where this belongs.

**Comment by benmonro** [comment] 2019-10-14 13:14
Yeah I hear you guys but that said they are only coupled to the respective expect styles as they relate to testing library.  If not this plugin then where?  The plugin already supports Vue and react right?  Testing library transcends platforms. That's what I love about it.  🤓

**Comment by Belco90** [comment] 2019-10-15 07:57
Leave me give this a try, I hope I can come back at the end of the week with something.

**Comment by Belco90** [comment] 2019-10-21 16:41
Still getting my head around this and not having so much spare time lately, so still working on this.

**Comment by Belco90** [comment] 2019-10-24 07:46
After `jest-dom-*` prefix I commented in #30 I'll repurpose this rule so it's just focused on jest-dom variant so we can code it simpler and even autofix the code. The only pending thing is to find a better name as `prefer-targeted-queries` sounds too generic, any suggestions?

**Comment by Belco90** [comment] 2019-12-03 15:06
Closing this one as it could be moved to the new eslint plugin I think.

**Closed by Belco90** 2019-12-03 15:06 UTC
Labels: new rule
